src/models/role.py
from db import db


# Define the Role data-model
class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), autoincrement=True, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)

    def __repr__(self):
        return f'<Role {self.name}>'


# Define the UserRoles association table
class UserRoles(db.Model):
    __tablename__ = 'user_roles'
    id = db.Column(db.Integer(), autoincrement=True, primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'))
    role_id = db.Column(db.Integer(), db.ForeignKey('roles.id', ondelete='CASCADE'))

src/models/user.py
from flask_login import UserMixin

from db import db
from models.role import *


class User(db.Model, UserMixin):
    """An admin user capable of viewing reports.

    :param str email: email address of user
    :param str password: encrypted password for the user

    """
    __tablename__ = 'users'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    email = db.Column(db.String(255), nullable=True, unique=True, info={"label": "Email"})
    password = db.Column(db.String(255), nullable=False)
    authenticated = db.Column(db.Boolean, default=False)

    # Define the relationship to Role via UserRoles
    roles = db.relationship('Role', secondary='user_roles')

    def __repr__(self):
        return f'<User email={self.email}>'

    def has_role(self, role: str) -> bool:
        return role in [r.name for r in self.roles]

    def is_active(self):
        """True, as all users are active."""
        return True

    def get_id(self):
        """Return the email address to satisfy Flask-Login's requirements."""
        return self.email

    def is_authenticated(self):
        """Return True if the user is authenticated."""
        return self.authenticated

    def is_anonymous(self):
        """False, as anonymous users aren't supported."""
        return False

src/app.py
from flask import Flask, render_template, redirect
from flask_login import login_required, current_user

from blueprints.admin import admin
from blueprints.base import base
from blueprints.exceptions import exc

from login import login_manager
from db import db

app = Flask(__name__)
app.config.from_object("config.Config")


db.init_app(app)
login_manager.init_app(app)

app.register_blueprint(exc)
app.register_blueprint(base, url_prefix="/")
app.register_blueprint(admin, url_prefix="/admin")


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/secure")
@login_required
def secure():
    return render_template("secure.html")


@app.route("/make_me_admin")
@login_required
def admin_maker():
    from models.role import Role

    admin_role = Role.query.filter_by(name="admin").first()

    if not admin_role:
        admin_role = Role(name="admin")
        db.session.add(admin_role)

    if "admin" not in current_user.roles:
        current_user.roles = [admin_role]

    db.session.commit()

    return redirect("/admin")


if __name__ == '__main__':
    app.run(debug=True)

src/blueprints/admin.py
from typing import Optional

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from sqlalchemy.orm import joinedload

from forms.admin.roles import ModifyRoleForm, RoleForm
from models.role import Role
from models.user import User
from util.decorators import role_required

admin = Blueprint("admin", __name__)


@admin.before_request
@login_required
@role_required("admin")
def before_request():
    # Protecting all admin Blueprint views to only admins
    pass


@admin.route("")
def index():
    return render_template("admin/index.html")


@admin.route("/users")
def users():
    _users = User.query.options(
        joinedload(User.roles)
    ).all()

    return render_template('admin/users.html', users=_users)


@admin.route("/roles")
def roles():
    return render_template("admin/roles.html")


@admin.route("/role/create", methods=["GET", "POST"])
def create_role():
    form = RoleForm()

    if form.validate_on_submit():
        from db import db

        role = Role(name=form.name.data)

        db.session.add(role)
        db.session.commit()

        return redirect(url_for('admin.create_role'))
    return render_template('admin/create_role.html', form=form)


@admin.route("/role/add", methods=["GET", "POST"])
def add_role():
    form = ModifyRoleForm()

    if form.validate_on_submit():
        from db import db
        user = form.email.data
        role = form.role.data

        if role not in user.roles:
            user.roles.append(role)

            db.session.commit()
            flash(f'"{role.name}" successfully added to {user.email}')
        else:
            flash(f'{user.email} is already an "{role.name}"')

        return redirect(url_for('admin.add_role'))

    return render_template('admin/modify_role.html', target_url=url_for("admin.add_role"), form=form)


@admin.route("/role/remove", methods=["GET", "POST"])
def remove_role():
    form = ModifyRoleForm()

    if form.validate_on_submit():
        from db import db
        user = form.email.data
        role = form.role.data

        if role in user.roles:
            user.roles.remove(role)

            db.session.commit()
            flash(f'"{role.name}" successfully removed to {user.email}')
        else:
            flash(f'{user.email} is not an "{role.name}"')

        return redirect(url_for('admin.remove_role'))
    return render_template('admin/modify_role.html', target_url=url_for("admin.remove_role"), form=form)

src/blueprints/base.py
from datetime import timedelta
from typing import Optional

import bcrypt as bcrypt
from flask import Flask, flash, request, abort, url_for, redirect, render_template, Blueprint
from flask_login import current_user, login_user, login_required, logout_user

from forms.user.login import LoginForm

base = Blueprint("base", __name__)


@base.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        from models.user import User

        user: Optional[User] = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.checkpw(form.password.data.encode(), user.password):
            from db import db

            user.authenticated = True
            login_user(user)

            db.session.commit()

            next_url = request.args.get("next")

            return redirect(next_url or url_for('index'))

        flash("Email or Password not correct.")
    return render_template('user/login.html', form=form)


@base.route("/logout")
@login_required
def logout():
    from flask_login import current_user
    from models.user import User
    from db import db

    User.query.get(current_user.id).authenticated = False
    logout_user()

    db.session.commit()
    return redirect("/")


@base.route("/register", methods=["GET", "POST"])
def register():
    from forms.user.register import RegisterForm

    form = RegisterForm()

    if form.validate_on_submit():
        from models.user import User
        from db import db

        user = User(email=form.email.data, password=bcrypt.hashpw(form.password.data.encode(), bcrypt.gensalt()))

        db.session.add(user)
        db.session.commit()

        next_url = request.args.get("next")

        return redirect(next_url or url_for('base.login'))
    return render_template('user/register.html', form=form)

src/blueprints/exceptions.py
from flask import Blueprint, render_template

exc = Blueprint("exception", __name__)


@exc.app_errorhandler(404)
def page_not_found(e):
    return render_template("exceptions/404.html"), 404

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}User POC{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
</head>
<body class="container">
<nav>
    <ul role="navigation">
        <li><a href="{{ url_for('index') }}">Home</a></li>
        {% if current_user.is_authenticated -%}
            {% if current_user.has_role('editor') -%}
            <li><a href="{{ url_for('secure') }}">Secure</a></li>
            {% endif -%}
            {% if current_user.has_role('admin') -%}
            <li><a href="{{ url_for('admin.index') }}">Admin Dashboard</a></li>
            {% endif -%}
        {% endif -%}
        <li class="nav__center"></li>
        {% if current_user.is_authenticated -%}
            <li>Hi {{ current_user.email }}!</li>
            <li><a href="/logout">Logout</a></li>
        {% else -%}
            <li>Hi Guest!</li>
            <li><a href="/login">Login</a></li>
            <li><a href="/register">Register</a></li>
        {% endif %}
    </ul>
</nav>
<hr>
{% block body %}{% endblock %}
</body>
</html>

src/templates/index.html
{% extends "base.html" %}
{% block body %}
<main>
    <header>
        <h2>Welcome to the user poc</h2>
    </header>
    <article>
        This will contain a basic environment required for this application
    </article>
</main>
{% endblock %}

src/templates/macros/forms.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

src/templates/secure.html
{% extends "base.html" %}
{% block body %}
<main>
    <header>
        <h2>Welcome to the user poc</h2>
    </header>
    <article>
        This will contain the secure environment required for this application
    </article>
</main>
{% endblock %}

src/templates/user/login.html
{% extends "base.html" %}
{% from "macros/forms.html" import render_field %}
{% block body %}
<form method="POST" action="/login">
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    <input type="submit" value="Login">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class=flashes>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
</form>
{% endblock %}

src/templates/user/register.html
{% extends "base.html" %}
{% from "macros/forms.html" import render_field %}
{% block body %}
<form method="POST" action="/register">
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ render_field(form.confirm) }}
    <input type="submit" value="Go">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class=flashes>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
</form>
{% endblock %}